Weinberg 2016 dataset 20
riboviz/example-datasets pull request #49
Opened 2021-02-15 11:10 UTC by 3mma-mack

Adding the config file for the Weinberg & Shah example dataset to fungi/saccharomyces in master following successful run on Eddie. 

#20

2021-02-17 19:09 UTC, ewallace commented
I _think_ the task is complete, but we might want to rethink a more precise name - e.g. what annotation does it go to?

2021-02-18 11:20 UTC, FlicAnderson commented
Nice, @swinterbourne you also fixed the sample number in the yaml name! 

I think this is ready to merge & close.

2021-02-18 11:37 UTC, FlicAnderson requested changes
Ooh, one last thing actually - can @swinterbourne or @3mma-mack update the 'date run' date and 'commit' hash? I think the latest run date is more recent than January, and it'd be good to confirm what the latest commit in the develop branch was that this was run with (you can check with 'git log -1' in the branch on Eddie).

2021-02-23 15:44 UTC, FlicAnderson approved these changes

2021-02-24 16:24 UTC, merged